// Runs real PostgreSQL RLS, grants, constraints, and triggers in isolated WASM.
// Supabase auth and storage schemas are minimal stubs, not live services.
import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
process.on('uncaughtException', error => { console.error('DATABASE TEST ERROR:', error.message, error.code ?? ''); process.exit(1); });
const db = new PGlite();
const root = new URL('../migrations/202610040001_municipality.sql', import.meta.url);
await db.exec(`
  create role anon; create role authenticated;
  create schema auth; create schema storage;
  create table auth.users(id uuid primary key);
  create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
  grant usage on schema auth,storage,public to anon,authenticated;
  grant execute on function auth.uid() to anon,authenticated;
  create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
  create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
  alter table storage.objects enable row level security;
  grant select,insert,update,delete on storage.objects to authenticated;
  create function storage.foldername(text) returns text[] language sql immutable as $$select (string_to_array($1,'/'))[1:array_length(string_to_array($1,'/'),1)-1]$$;
`);
// Exercise the upgrade path using the original schema and an existing row.
await db.exec(`
  create table public.requests(id uuid primary key default gen_random_uuid(),resident_id uuid not null references auth.users(id) on delete cascade,request_type text not null check(request_type in ('issue_report','service_request')),category text not null,description text not null,location_text text,contact_phone text,has_photo boolean not null default false,status text not null default 'received' check(status in ('received','in_progress','resolved','rejected')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
  alter table public.requests enable row level security;
  create policy "Residents can create their own requests" on public.requests for insert to authenticated with check(auth.uid()=resident_id);
  create policy "Residents can view their own requests" on public.requests for select to authenticated using(auth.uid()=resident_id);
  create policy "Residents can update their own received requests" on public.requests for update to authenticated using(auth.uid()=resident_id and status='received') with check(auth.uid()=resident_id and status='received');
`);
const resident='10000000-0000-0000-0000-000000000001';
const other='10000000-0000-0000-0000-000000000002';
const staff='10000000-0000-0000-0000-000000000003';
const outsider='10000000-0000-0000-0000-000000000004';
const admin='10000000-0000-0000-0000-000000000005';
for (const id of [resident,other,staff,outsider,admin]) await db.query('insert into auth.users values($1)',[id]);
await db.query(`insert into public.requests(resident_id,request_type,category,description) values($1,'issue_report','أخرى','old')`,[resident]);
await db.exec(await readFile(root,'utf8'));
let passed=0;
const login=async(id)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id??'']);await db.exec(id?'set role authenticated':'set role anon');};
const scalar=async(sql,params=[])=>Object.values((await db.query(sql,params)).rows[0])[0];
const check=(name,value)=>{assert.ok(value,name);console.log(`PASS ${name}`);passed++;};
const denied=async(name,sql,params=[])=>{let error;try{await db.query(sql,params);}catch(e){error=e;}check(name,!!error);};
await db.exec(`insert into public.staff_members(user_id,role,department_id) values('${admin}','admin',null),('${staff}','staff',(select id from public.departments where name='الصيانة')),('${outsider}','staff',(select id from public.departments where name='الأشغال'))`);
const requestId='20000000-0000-0000-0000-000000000001';
const photo=`${resident}/${requestId}/photo.jpg`;
await login(resident);
check('legacy request preserved',await scalar('select count(*)::int from public.requests')===1);
await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['request-photos',photo]);
await db.query(`insert into public.requests(id,resident_id,request_type,category,description,photo_path) values($1,$2,'issue_report','إنارة الشوارع','Street light needs repair',$3)`,[requestId,resident,photo]);
await denied('missing photo cannot be linked', `insert into public.requests(resident_id,request_type,category,description,photo_path) values($1,'issue_report','مياه','A leaking water pipe',$2)`,[resident,`${resident}/missing/photo.jpg`]);
check('new request starts received',await scalar('select status from public.requests where id=$1',[requestId])==='received');
check('photo flag derived on server',await scalar('select has_photo from public.requests where id=$1',[requestId])===true);
await denied('resident cannot forge status on insert',`insert into public.requests(resident_id,request_type,category,description,status) values($1,'issue_report','أخرى','Forged resolved request','resolved')`,[resident]);
await denied('resident cannot forge ownership',`insert into public.requests(resident_id,request_type,category,description) values($1,'issue_report','أخرى','Forged owner request')`,[other]);
await denied('resident cannot update request',`update public.requests set status='resolved' where id=$1`,[requestId]);
await denied('resident cannot promote self',`insert into public.staff_members(user_id,role) values($1,'admin')`,[resident]);
await denied('resident cannot use role RPC',`select public.manage_member($1,'admin',null)`,[resident]);
await denied('resident cannot update through staff RPC',`select public.update_request($1,'resolved',null,null)`,[requestId]);
check('linked photo cannot be replaced',(await db.query('update storage.objects set name=$1 where name=$1 returning id',[photo])).rows.length===0);
check('linked photo cannot be deleted',(await db.query('delete from storage.objects where name=$1 returning id',[photo])).rows.length===0);
await denied('photo path cannot use another account',`insert into storage.objects(bucket_id,name) values('request-photos',$1)`,[`${other}/photo.jpg`]);
await login(other);
check('other resident cannot read request',await scalar('select count(*)::int from public.requests where id=$1',[requestId])===0);
check('other resident cannot read history',await scalar('select count(*)::int from public.request_history where request_id=$1',[requestId])===0);
check('other resident cannot read photo',await scalar('select count(*)::int from storage.objects where name=$1',[photo])===0);
await login(outsider);
check('other department cannot read request',await scalar('select count(*)::int from public.requests where id=$1',[requestId])===0);
await denied('other department cannot update request',`select public.update_request($1,'resolved',null,null)`,[requestId]);
check('other department cannot read photo',await scalar('select count(*)::int from storage.objects where name=$1',[photo])===0);
await login(staff);
check('department metrics reflect allowed requests',(await scalar('select public.request_metrics()')).total === 1);
check('assigned staff can read request',await scalar('select count(*)::int from public.requests where id=$1',[requestId])===1);
check('assigned staff can read photo',await scalar('select count(*)::int from storage.objects where name=$1',[photo])===1);
await db.query(`select public.update_request($1,'in_progress','Repair scheduled',null)`,[requestId]);
check('staff status update persisted',await scalar('select status from public.requests where id=$1',[requestId])==='in_progress');
check('status update audit actor recorded',await scalar("select count(*)::int from public.request_history where request_id=$1 and actor_id=$2 and status='in_progress'",[requestId,staff])===1);
const otherDept=await scalar("select id from public.departments where name='الأشغال'");
await denied('staff cannot reassign department',`select public.update_request($1,'in_progress',null,$2)`,[requestId,otherDept]);
await denied('staff cannot publish content',`insert into public.public_content(kind,title,published) values('announcement','Staff content',true)`);
await login(admin);
await db.query(`select public.update_request($1,'resolved','Repair completed',$2)`,[requestId,otherDept]);
check('admin can reassign department',await scalar('select department_id from public.requests where id=$1',[requestId])===otherDept);
await denied('last administrator cannot be demoted',`select public.manage_member($1,'resident',null)`,[admin]);
await db.query(`select public.manage_member($1,'staff',$2)`,[other,otherDept]);
check('admin role changes are audited',await scalar('select count(*)::int from public.role_audit where target_id=$1',[other])===1);
await db.exec(`insert into public.public_content(kind,title,published) values('announcement','Published',true),('announcement','Draft',false)`);
await login(null);
check('anonymous sees published content only',await scalar('select count(*)::int from public.public_content')===1);
await denied('anonymous cannot read private requests','select * from public.requests');
await login(admin);
const poll=(await db.query("insert into public.polls(question,options,closes_at,published) values('Priority?','[\"Roads\",\"Lighting\"]',now()+interval '1 day',true) returning id")).rows[0].id;
await denied('poll options must be strings',"insert into public.polls(question,options,closes_at) values('Bad','[1,2]',now()+interval '1 day')");
await login(resident);
await db.query('insert into public.poll_votes(poll_id,voter_id,option_index) values($1,$2,0)',[poll,resident]);
await denied('account cannot vote twice','insert into public.poll_votes(poll_id,voter_id,option_index) values($1,$2,1)',[poll,resident]);
await denied('account cannot impersonate voter','insert into public.poll_votes(poll_id,voter_id,option_index) values($1,$2,1)',[poll,other]);
await login(other);
await denied('invalid option rejected','insert into public.poll_votes(poll_id,voter_id,option_index) values($1,$2,7)',[poll,other]);
check('vote identities private',await scalar('select count(*)::int from public.poll_votes')===0);
check('aggregate results visible',Number((await db.query('select * from public.poll_results($1)',[poll])).rows[0].votes)===1);
await login(admin);
const closed=(await db.query("insert into public.polls(question,options,closes_at,published) values('Closed?','[\"A\",\"B\"]',now()-interval '1 day',true) returning id")).rows[0].id;
const invoice=(await db.query("insert into public.invoices(resident_id,title,amount) values($1,'Collection fee',20.50) returning id",[resident])).rows[0].id;
await login(resident);
await denied('closed poll rejects vote','insert into public.poll_votes(poll_id,voter_id,option_index) values($1,$2,0)',[closed,resident]);
check('resident sees own invoice',await scalar('select count(*)::int from public.invoices')===1);
await denied('resident cannot mark invoice paid',"select public.record_payment($1,'FAKE')",[invoice]);
await denied('resident cannot forge paid invoice',"insert into public.invoices(resident_id,title,amount,status) values($1,'Fake',1,'paid')",[resident]);
await login(other);
check('resident cannot see someone elses invoice',await scalar('select count(*)::int from public.invoices')===0);
await login(admin);
await denied('receipt reference required',"select public.record_payment($1,'')",[invoice]);
await db.query("select public.record_payment($1,'OFFICIAL-RECEIPT-001')",[invoice]);
check('payment verification actor saved',await scalar('select verified_by from public.invoices where id=$1',[invoice])===admin);
await denied('paid invoice cannot be reverified',"select public.record_payment($1,'SECOND')",[invoice]);
await login(resident);
check('resident metrics do not expose departmental records',(await scalar('select public.request_metrics()')).total === 0);
check('resident sees updated status',await scalar('select status from public.requests where id=$1',[requestId])==='resolved');
console.log(`${passed} database security checks passed`);
await db.close();
